// Each entry is [date, English title, Japanese title, English detail, Japanese detail].
// Dates without a reliable year remain explicitly unspecified.
import { codexHackathon } from "./events.mjs";

export const archiveGroups = [
  {
    id: "research",
    title: ["Research & development", "研究・開発"],
    entries: [
      [
        "2020–2021",
        "Wind-based artificial gravity",
        "風力を用いた人工重力機構",
        "An SSH independent project explored whether airflow could reproduce loading on the body in microgravity. I calculated internal stresses, built an Arduino-based force sensor, and tested a prototype. The analysis suggested that equivalent loading was limited to the soles of the feet; the discrepancy increased higher in the body, identifying a need to improve the approach.",
        "SSHの個人研究として、風力による身体への荷重が微小重力環境で利用できるかを検討。人体に働く応力を数値計算し、Arduinoによる測定器とプロトタイプを製作しました。足裏付近以外では重力下との応力の差が大きくなると推測され、改善が必要な点を明らかにしました。",
      ],
      [
        "2021.12.19",
        "Intelligent Water Rocket Competition",
        "知能化水ロケット競技会",
        "As SeSDA representative, I led development of the rocket, onboard electronics, and launcher, as well as communication and budget management. Our missions included parachute deployment, airborne filming, and deployment of an onboard satellite and its parachute. All missions succeeded, earning the Missions Award.",
        "SeSDA代表として、ロケット本体・電子機器・発射機の開発に加え、連絡調整と収支管理を担当。パラシュート展開、空中撮影、搭載衛星の放出と衛星のパラシュート展開など、設定した全ミッションを成功させ、ミッション賞を受賞しました。",
      ],
      [
        "2020.12–2023.03",
        "Extreme halophiles at ELSI",
        "ELSIでの高度好塩菌研究",
        "After discovering astrobiology through online seminars, I contacted researchers and joined Kosuke Fujishima’s lab at Tokyo Tech. With Keio GSC / JST support, I isolated archaea under varied culture conditions and performed DNA and phylogenetic analysis. In one analysis, eight colonies yielded five identified species. The project included rock salt from nine countries and 55 culture conditions.",
        "オンライン講演をきっかけに宇宙生物学に関心を持ち、研究者へ連絡して東京工業大学・藤島研究室で研究を開始。慶應GSC・JSTの支援のもと、条件を変えて岩塩から微生物を単離し、DNA・系統解析を実施。8個のコロニーから5種を確認し、9か国の岩塩、55種類の培地条件を対象とする培養にも取り組みました。",
      ],
      [
        "2021–2022",
        "International meteorite research",
        "英国の高校との隕石共同研究",
        "Collaborated with a UK high school and university researchers on meteorite composition and organic material. Used scanning electron microscopy and presented in English at International Research for School.",
        "英国の高校・大学教員と隕石の組成や有機物を対象とする共同研究に参加。走査電子顕微鏡を用いた分析と、International Research for Schoolでの英語発表を経験しました。",
      ],
      [
        "2023–2024",
        "Microbial metabolism",
        "微生物の代謝経路",
        "Wet-lab research at Kyoto University’s Atomi Lab on microbial pathways for hydrogen and oxygen utilization.",
        "京都大学・跡見研究室で、水素・酸素の利用に関わる微生物の代謝経路についてウェットラボ研究に取り組みました。",
      ],
      [
        "2024.08–",
        "Georgia Tech: metagenomic analysis",
        "ジョージア工科大学・メタゲノム解析",
        "At Thomas DiChristina’s lab, analyzed wetland microbial communities relevant to Savannah River Site remediation. Used Python and R to study the effects of Fe(III), sulfate, and pH buffers. Explored a possible role of organic sulfur shuttles in metal reduction; this was a research hypothesis, not a confirmed mechanism. Continued collaboration remotely after the visit.",
        "Thomas DiChristina研究室で、サバンナリバーサイトの環境浄化に関連する湿地堆積物の微生物群集を解析。Python・RでFe(III)、硫酸塩、pHバッファ添加の影響を調べ、金属還元に有機硫黄シャトルが関わる可能性を検討しました。現地滞在後もリモートで研究を継続しています。",
      ],
      [
        "2025.02–04",
        "DFKI: robot arm control",
        "DFKI・ロボットアーム制御",
        "At DFKI Bremen’s Robotics Innovation Center, built Drake simulation environments and controllers for a 7-DOF arm. Considered contact dynamics in the context of spacecraft capture and debris removal. Fully funded through the Nakatani Foundation.",
        "DFKIブレーメンのRobotics Innovation Centerで、7自由度アームのDrakeシミュレーション環境と制御器を開発。宇宙機捕獲・デブリ除去を背景に、接触時の反動を考慮する制御に取り組みました。中谷財団の全額給付型奨学金で派遣。",
      ],
      [
        "2025–",
        "Athletics record management web app",
        "陸上部の記録管理Webアプリ",
        "Replaced an Excel-based input and website-update workflow with a React / Firebase web application. Focused on understandable interfaces, automatic aggregation, readable code, and maintainability for a team without a permanent technical specialist. The application is in trial use and is being improved with member feedback.",
        "大会ごとのExcel入力とホームページ更新を行っていた業務を、React・FirebaseによるWebサービスへ。専任の技術者が常にいるわけではない部の事情を踏まえ、分かりやすいUI・自動集計・保守しやすいコードを重視。部内で試用し、利用者の声をもとに改善しています。",
      ],
      [
        "2025.03–",
        "Russian grammatical error correction",
        "ロシア語の文法誤り訂正AI",
        "Software engineering internship at Tleez, developing machine learning models for natural language processing and generating training data.",
        "株式会社Tleezのエンジニアインターンとして、自然言語処理による文法誤り訂正AIと学習データ生成を担当しています。",
      ],
      [
        "2025.08–",
        "Mission design at JAXA ISAS",
        "JAXA ISASでのミッション設計",
        "Trajectory analysis for multi-point outer-planet observations and development of low-thrust optimization methods with Julia and DDP / HDDP.",
        "外惑星探査機による多点同時観測に向けた軌道解析と、Julia・DDP／HDDPによる低推力軌道最適化手法を研究しています。",
      ],
      [
        "2025.10–",
        "Lunar robot learning and control",
        "月面ロボットの学習と制御",
        "Reinforcement learning, inverse kinematics, system identification, and sim-to-real development for modular multi-legged robots in Kyoto University’s Learning Machines Group.",
        "京都大学・学習機械制御論分野で、多脚モジュールロボットの強化学習、逆運動学、システム同定、Sim-to-Real環境構築を担当しています。",
      ],
      [
        "2026.04–",
        "Transformer models and nonlinear MPC",
        "Transformerモデルと非線形MPC",
        "Undergraduate work in Kenji Fujimoto’s control engineering group. Integrated a Transformer-based model into nonlinear predictive control and implemented real-time tracking on an RC car.",
        "藤本健治研究室の学部研究として、Transformerで同定したモデルを非線形モデル予測制御へ統合し、ラジコンカーの実時間自動追従を実機に実装しました。",
      ],
      [
        "—",
        "Illuminated safety slippers",
        "足元を照らす防災スリッパ",
        "Conceived, designed, and prototyped slippers with lights to illuminate the floor during nighttime disasters and power outages.",
        "夜間の災害や停電時に足元を照らすライト付きスリッパを考案・設計し、プロトタイプを製作しました。",
      ],
      [
        "—",
        "A sports-science training plan",
        "スポーツ科学に基づくトレーニング計画",
        "Created a training plan for a beginner volleyball player based on sports-science principles and assessed the results.",
        "バレーボール初心者に向け、スポーツ科学的な根拠に基づいたトレーニング計画を作成し、その成果を測定しました。",
      ],
    ],
  },
  {
    id: "leadership",
    title: ["Initiatives & leadership", "企画・運営・社会との接点"],
    entries: [
      [
        "2020–2023",
        "Seiko Space Development Association",
        "聖光宇宙開発研究会（SeSDA）代表",
        "Led activities spanning satellite design competitions, water rockets, school-festival exhibitions, space-food sales, publications, school exchanges, events, museum visits, and poster design. The club was featured in newspapers.",
        "代表として、衛星設計コンテスト、水ロケット、文化祭展示、宇宙食販売、部誌制作、他校交流、イベント、博物館見学、ポスター制作などを発案・実行。新聞などの取材も受けました。",
      ],
      [
        "2021.02.20",
        "Kanto Online Science Club Summit",
        "関東オンラインサイエンスクラブサミット",
        "Founded an online event to restore inter-school connections during the pandemic. Contacted schools individually, invited university students with school-research experience, and brought students together around shared challenges in inquiry-based learning.",
        "コロナ禍で減った他校交流を取り戻すため、一からオンラインイベントを立ち上げました。各校へ連絡し、高校時代に研究活動をしていた大学生を招き、探究活動の共通の悩みを共有する場をつくりました。",
      ],
      [
        "2021.06",
        "National School Students Space Forum",
        "全国中高生宇宙フォーラム",
        "Co-organized with Hiroo Gakuen, inviting professors from Tokyo University of Science and Tohoku University. Held over two days, with around 100 school students attending each day.",
        "広尾学園と協力し、東京理科大学・東北大学の教授を招いてオンラインイベントを開催。2日間にわたり、両日とも100名近くの中高生が参加しました。",
      ],
      [
        "2021.10",
        "Seiko SDGs Food Ambassador",
        "Seiko SDGs Food Ambassador",
        "Founded a project supporting tourism businesses and reducing food loss during COVID-19. Negotiated with regional producers, arranged logistics, coordinated the school festival, and planned sales. All products sold out; the initiative received media coverage and the Nihon Ryoko Prize at the SDGs Tankyu Award.",
        "観光産業支援とフードロス削減を目指し、地方の直売所・土産物店の余剰商品を買い取り文化祭で販売する企画を創設。事業者交渉、物流、実行委員会との調整、販売計画を主導し、全商品を完売。取材やSDGs探究Award日本旅行賞につながりました。",
      ],
      [
        "2021.10",
        "School festival food operations",
        "聖光祭・食品副部門長",
        "Oversaw procurement, space-food sales, the SDGs Food Ambassador project, and COVID-19 measures. Coordinated twelve food stalls, with electronic payments and online reservations; all stalls sold out.",
        "仕入れ、宇宙食販売、SDGs Food Ambassador、コロナ対策を担当。12店舗の模擬店を総括し、電子決済やオンライン予約を導入。全店舗の完売につなげました。",
      ],
      [
        "School years",
        "Chocolate-banana pop-up",
        "チョコバナナの模擬店",
        "Founded a new school-festival stall and managed sales of 3,800 chocolate bananas over two days.",
        "中学1年生の文化祭で新しい模擬店を立ち上げ、店長として2日間で3,800本のチョコバナナを販売しました。",
      ],
      [
        "2025.11",
        "Startup Weekend Space Osaka",
        "Startup Weekend Space Osaka 5th",
        "Led a multidisciplinary team through 54 hours of business-plan and prototype development and pitching, winning second place.",
        "チームリーダーとして進行管理・タスク調整を行い、54時間で宇宙ビジネス案とプロトタイプを開発・発表。準優勝を獲得しました。",
      ],
      [
        "2012–",
        "Traditional rice farming",
        "「田んぼの時間」での伝統的稲作",
        "Participated for more than twelve years in Koganei’s Tanbo no Jikan rice-farming circle. Helped staff guide newcomers through traditional pesticide-free rice farming.",
        "小金井市環境市民会議「田んぼの時間」に12年以上参加。スタッフ側として未経験者を案内しながら、無農薬の伝統的な米づくりに取り組んでいます。",
      ],
      [
        "2021.08",
        "ICAS legislative internship",
        "ICAS・東京都議会での議員インターン",
        "Interned at the office of Tokyo Metropolitan Assembly Vice-Chairperson Motohashi. Observed assembly and office work, helped with constituency activities, and gave a street speech on future space development and politics.",
        "東京都議会副議長・本橋氏の事務所でインターン。都議会・都庁・事務所の業務を見学し、地域での活動を手伝いました。駅前で将来の宇宙開発と政治についてスピーチも行いました。",
      ],
      [
        "2023.08",
        "Space medicine study tour",
        "京都大学宇宙医学スタディツアー",
        "Organized a study tour for university students and engaged with a nationwide student community in space medicine.",
        "大学生に向けた宇宙医学スタディツアーを企画・運営。宇宙医学の学生コミュニティでも活動しました。",
      ],
      [
        "2023.12 / 2025.11",
        "International symposium operations",
        "国際シンポジウム・学会運営",
        "Supported the 7th Global Moon Village Workshop and the 71st Japan Society of Aerospace and Environmental Medicine meeting.",
        "第7回Global Moon Village Workshopと第71回日本宇宙航空環境医学会大会の運営をサポートしました。",
      ],
      [
        "2020.07–",
        "Moon Village study group",
        "ムーンビレッジ研究会",
        "Participated from the first meeting on July 31, 2020.",
        "2020年7月31日の第1回から研究会に参加しています。",
      ],
    ],
  },
  {
    id: "exchange",
    title: ["Exchange, teaching & culture", "国際交流・教育・文化"],
    entries: [
      [
        "2019",
        "India–Japan student space discussion",
        "日印・次世代宇宙技術オンライン会議",
        "Independently planned, recruited for, and ran a discussion for Indian and Japanese students. Topics expanded from space technology to politics, international cooperation, and environmental protection.",
        "日本とインドの中高生を集め、将来の宇宙開発を考えるオンライン会議を企画・集客・運営。技術だけでなく、政治、国際協力、環境保全まで学際的な議論が広がりました。",
      ],
      [
        "2026.03",
        "JENESYS2025 Japan–Korea exchange",
        "JENESYS2025・日韓青少年交流訪韓団",
        "Selected delegate in a program supported by Japan’s Ministry of Foreign Affairs and the Japan–Korea Cultural Foundation.",
        "外務省・日韓文化交流基金によるプログラムの派遣団員として、韓国で異文化交流に参加しました。",
      ],
      [
        "2025.05",
        "Interpreter for international musicians",
        "京都・国際音楽学生フェスティバル通訳",
        "Provided English–Japanese interpretation and liaison support for musicians from Germany, Italy, the US, France, and other countries over a one-week festival. Coordinated schedules and local guidance.",
        "1週間にわたり、ドイツ・イタリア・米国・フランスなどの音楽家を英日通訳・アテンド。滞在中の案内、主催者との連絡、スケジュール調整を担当しました。",
      ],
      [
        "2023.06–",
        "Mathematics instruction at Tetsuryokukai",
        "鉄緑会・数学科講師",
        "Teach advanced high-school mathematics, manage classes, and communicate with parents. Adapt explanations to students’ understanding.",
        "難関大学志望の高校生への数学指導に加え、教室運営や保護者対応を担当。理解度に合わせた説明を工夫しています。",
      ],
      [
        "2020",
        "Free online mathematics classes",
        "インドの後輩への無料オンライン数学教室",
        "During COVID-19 stay-at-home periods, taught calculus, trigonometry, and logarithms to younger students in India.",
        "コロナ禍のSTAYHOME期間に、インドの後輩へ微積分・三角関数・対数などを教える無料オンライン教室を開きました。",
      ],
      [
        "2019",
        "Japanese calligraphy workshop",
        "日本の書道を伝える体験イベント",
        "Ran a school cultural-event booth in India, writing participants’ names in Japanese calligraphy and introducing the activity in English.",
        "インドの学校行事で、参加者の名前を習字で書く体験企画を実施。英語で日本の書道文化を紹介しました。",
      ],
      [
        "2018–2020",
        "School choir and performance",
        "Pathways School Gurgaon・合唱と舞台",
        "Participated in the school choir and productions including Mamma Mia.",
        "学校の合唱団に所属し、Mamma Miaなどの舞台にも参加しました。",
      ],
      [
        "2021.10",
        "Writing and performing on stage",
        "聖光祭・台本制作と舞台出演",
        "Wrote scripts, devised staging, and performed manzai, ukulele comedy, and a comic play at the school festival.",
        "しゃべくり漫才、ウクレレ漫談、喜劇の台本作成・演出考案・出演を担当しました。",
      ],
      [
        "—",
        "Discussing the future of education",
        "WWL・APU国際学生との教育討論",
        "Joined an English-language discussion with WWL partner schools and APU international students on how education should develop.",
        "WWL連携校とAPU国際学生との英語ディスカッションで、教育の在り方について討論しました。",
      ],
      [
        "—",
        "Listening to social initiatives in India",
        "インドでの社会支援活動との対話",
        "Visited and spoke with a person supporting low-wage workers and people experiencing homelessness in India.",
        "インドの低賃金労働者やホームレスの方を支援する活動者を訪問し、対話しました。",
      ],
      [
        "—",
        "Japanese New Year in the school newspaper",
        "学校新聞で日本のお正月を紹介",
        "Contributed an article introducing Japanese New Year traditions to the wider school community in India.",
        "インドの学校新聞に、日本の正月文化を紹介する記事を書きました。",
      ],
      [
        "2022",
        "JAXA Hello Explorer reporter",
        "JAXA Hello Explorer project・高校生記者",
        "Participated as a high-school reporter and contributed an article to TELSTAR space magazine.",
        "高校生記者として参加し、宇宙フリーマガジンTELSTARへ記事を寄稿しました。",
      ],
      [
        "2019",
        "Travel through local food",
        "旅先の食文化に触れる",
        "Spent about a quarter of the year away from home, making a point of trying local food in each place.",
        "1年の約4分の1を旅行などで自宅以外に滞在し、訪れた土地のローカルフードを味わいました。",
      ],
      [
        "—",
        "Hospitality and food service",
        "接客・飲食の現場経験",
        "Worked in bakery production, a Japanese restaurant kitchen, a coffee shop, and as a bartender.",
        "パン製造、和食店の厨房、コーヒーショップ、バーテンダーなどの現場を経験しました。",
      ],
      [
        "—",
        "Remembering the war",
        "戦争の記憶に向き合う",
        "Participated occasionally in commemorations for those who died in wartime special-attack missions.",
        "太平洋戦争の特攻隊で亡くなった方々への追悼に、不定期に参加しました。",
      ],
    ],
  },
  {
    id: "sport",
    title: ["Sport", "スポーツ"],
    entries: [
      [
        "2018",
        "National Shorinji Kempo championship",
        "少林寺拳法・全国中学生大会",
        "Competed in the national junior-high championship in pair / group performance. Practicing since 2012.",
        "中学2年時に全国中学生大会へ出場（組演武・団体演武）。2012年から競技に取り組んでいます。",
      ],
      [
        "2018–2020",
        "Running in India",
        "インドでの陸上競技",
        "Member of the India Japanese Association running club and Pathways School Gurgaon athletics team. Selected as the next team captain, but the appointment did not take place because of the COVID-19 lockdown.",
        "インド日本人会走友会とPathways School Gurgaon陸上部に所属。次期主将に選ばれましたが、コロナのロックダウンにより就任には至りませんでした。",
      ],
      [
        "2019.02.22",
        "Inter-house cross-country · 6th",
        "校内クロスカントリー・6位",
        "Sixth place in the Grade 8–9 boys’ 3200m at the 2018–2019 inter-house competition.",
        "2018–2019年度、Grade 8・9男子3200mで6位。",
      ],
      [
        "2019.04.22",
        "Inter-school 800m · 1st",
        "学校対抗陸上800m・優勝",
        "Won the 800m at an inter-school athletics competition in India.",
        "インドの学校対抗陸上競技会で800m優勝。",
      ],
      [
        "2019.06.09",
        "Yokohama Weekend Marathon · 3rd",
        "横浜ウィークエンドマラソン・3位",
        "Third place in the men’s 5km at the first Yokohama Weekend Marathon at Akarenga.",
        "第1回横浜ウィークエンドマラソンin赤レンガの5km男子で3位。",
      ],
      [
        "2019.07–08",
        "Haryana U17 1500m",
        "ハリヤナ州U17・1500m",
        "Second at Gurgaon block level on July 29; fourth at district level on August 22.",
        "7月29日のグルガオン地区ブロック大会で2位、8月22日の地区大会で4位。",
      ],
      [
        "2019.09.22",
        "Harvest Global Energy Run · 1st",
        "Harvest Global Energy Run・優勝",
        "Won the men’s open-age 5km.",
        "年齢制限なしの男子5kmで優勝。",
      ],
      [
        "2019",
        "ISSO National Games · Three golds",
        "ISSO全国大会・3冠",
        "Won 800m, 1500m, and 3000m at India’s international-school national games. Second in the 4×100m and 4×400m relays.",
        "インドのインターナショナルスクール全国大会で800m・1500m・3000m優勝。4×100m・4×400mリレーは2位。",
      ],
      [
        "2020.02",
        "MYP cross-country · Record win",
        "MYPクロスカントリー・大会新で優勝",
        "Won the MYP cross-country race with a new record.",
        "大会新記録で優勝しました。",
      ],
      [
        "2020.02",
        "Annual athletics individual champion",
        "年間陸上競技会・個人総合優勝",
        "Under-17 boys: first in 800m and 1500m, third in 400m; overall individual champion.",
        "U17男子400mで3位、800m・1500mで優勝し、個人総合優勝。",
      ],
      [
        "2021.11.07",
        "Yurikamome Relay Marathon · Overall win",
        "第11回ゆりかもめリレーマラソン・総合優勝",
        "A six-person SeSDA team, from junior-high second year to high-school second year, completed approximately 20.8km in 1:06:59 to win among 56 teams.",
        "中2〜高2の6人でSeSDAチームとして出場。約20.8kmを1時間06分59秒で走り、56チームの中で総合優勝しました。",
      ],
      [
        "2020",
        "Online training during lockdown",
        "休校中のオンライントレーニング",
        "Gathered friends from sports clubs to share home-training results when club activities stopped, supporting performance and motivation.",
        "部活動休止中、運動部の友人と筋トレ結果をオンライン共有し、パフォーマンスとモチベーションの維持を図りました。",
      ],
      [
        "—",
        "School festival club relay",
        "体育祭・部活対抗リレー",
        "Represented SeSDA in the competitive division: second in the qualifier and fourth in the final.",
        "SeSDAとして競技枠に出場。予選2位通過、決勝4位。",
      ],
      [
        "—",
        "National qualification and eligibility",
        "インド陸上・全国大会出場権",
        "Qualified for a national athletics competition in India but did not compete because of a nationality-related eligibility issue. This is separate from the ISSO school competition results.",
        "インドの陸上大会で全国大会出場権を獲得しましたが、国籍に関わる出場資格の問題で欠場。ISSOの学校競技大会とは別の実績です。",
      ],
    ],
  },
  {
    id: "learning",
    title: ["Awards, talks & learning", "受賞・発表・学び"],
    entries: [
      [
        "2026.08",
        "70th UKAREN · Paper submitted",
        "第70回宇宙科学技術連合講演会・論文投稿",
        "Submitted a paper on HDDP-based low-thrust trajectory optimization from GTO to GEO. Listed as submitted; acceptance or presentation is not implied.",
        "「GTOからGEOへの低推力軌道遷移におけるHDDPを用いた軌道最適化」を投稿。採択・発表済みではなく、投稿段階として記載しています。",
      ],
      [
        "2026.03",
        "SPS 2026 · Oral presentation",
        "惑星圏シンポジウム2026・口頭発表",
        "Presented mission design for simultaneous multi-point observations with ultra-small outer-planet probes sharing large overseas missions.",
        "「海外大型ミッション相乗りを想定した超小型外惑星探査機の多点同時観測のミッション設計」を口頭発表。",
      ],
      [
        "2024–2025",
        "Nakatani Foundation scholarship",
        "中谷財団・全額給付型海外留学奨学金",
        "Selected for funded research visits to Georgia Tech in the United States and DFKI in Germany.",
        "米国ジョージア工科大学・ドイツDFKIへの短期研究留学に全額給付型奨学生として派遣。",
      ],
      [
        "2023.11",
        "69th JSAEM · Oral and poster",
        "第69回日本宇宙航空環境医学会・発表",
        "Oral and poster presentation on the current state and prospects of space medicine education in Japan.",
        "日本における宇宙医学教育の現状と展望について口頭・ポスター発表。",
      ],
      [
        "2023.09",
        "Marine biology and space medicine",
        "琉球大学臨海実習・宇宙医学実習",
        "Joined a University of the Ryukyus marine biology program and Kyoto University’s space medicine training at Oita University, exploring physiology, marine ecology, and adaptation to extreme environments.",
        "琉球大学の臨海実習、京都大学の宇宙医学実習（大分大学）に参加。生理学、海洋生態、極限環境への適応について学びました。",
      ],
      [
        "2022.06.14",
        "Research presentation to NASA researchers",
        "NASA研究者への英語研究発表",
        "Presented astrobiology research in English to American NASA researchers.",
        "米国NASAの研究者に、宇宙生物学の研究を英語で発表しました。",
      ],
      [
        "2022.05.22",
        "JpGU · Excellent presentation award",
        "JpGU高校生発表・優秀賞",
        "Awarded for research isolating and identifying extreme halophiles from rock salt.",
        "岩塩からの高度好塩菌の単離と同定に関する研究で受賞。",
      ],
      [
        "2022.03.28",
        "Fisheries Society · Excellent presentation",
        "日本水産学会高校生発表・優秀賞",
        "Received an award for the high-school research presentation on extreme halophiles.",
        "極限環境微生物に関する高校生研究発表で受賞。",
      ],
      [
        "2022.02",
        "SDGs Tankyu Award · Nihon Ryoko Prize",
        "SDGs探究Award・日本旅行賞",
        "The Seiko SDGs Food Ambassador initiative received the Nihon Ryoko special prize in a competition with more than 2,400 entries.",
        "応募総数2,400件以上の中から、Seiko SDGs Food Ambassadorの活動が株式会社日本旅行の特別賞を受賞。",
      ],
      [
        "2021.10",
        "GSC national presentation",
        "GSC全国受講生研究発表会",
        "Presented the astrobiology research conducted through the Global Science Campus program.",
        "グローバルサイエンスキャンパスで取り組んだ宇宙生物学研究を発表しました。",
      ],
      [
        "2021.07–08",
        "SSH research presentation",
        "SSH研究発表",
        "Selected to present the wind-based artificial gravity study in the school auditorium; recognized at the SSH research symposium.",
        "風力を用いた人工重力の研究が選ばれ、講堂で発表。SSH研究発表会で評価を受けました。",
      ],
      [
        "2021.02.14",
        "Global English Award",
        "Global English Award 2021",
        "Block winner and Special Jury Prize.",
        "ブロック優勝・審査員特別賞を受賞。",
      ],
      [
        "2018.10.01",
        "Mathematics Inquiry Fair · 1st",
        "Math Inquiry Fair・優勝",
        "First place for a presentation on the Tower of Hanoi at Pathways School Gurgaon.",
        "Pathways School Gurgaonで、ハノイの塔に関するプレゼンテーションが1位。",
      ],
      [
        "2021.08",
        "KEK Belle Plus",
        "KEK Belle Plus 素粒子キャンプ",
        "Completed the particle physics camp at KEK.",
        "高エネルギー加速器研究機構の素粒子キャンプを修了。",
      ],
      [
        "2021.07–08",
        "National SR Summit FOCUS2021",
        "全国高校生SRサミット FOCUS2021",
        "Completed the fourth national high-school SR Summit.",
        "第4回全国高校生SRサミットを修了。",
      ],
      [
        "2021.07",
        "Chemistry Grand Prix",
        "化学グランプリ",
        "Participated in the Chemistry Grand Prix.",
        "化学グランプリに出場しました。",
      ],
      [
        "2020 / 2021",
        "Satellite Design Contest",
        "衛星設計コンテスト",
        "Participated for two consecutive years.",
        "2年連続で出場しました。",
      ],
      [
        "2021",
        "Keio Astrobiology Camp",
        "Keio Astrobiology Camp",
        "Completed the astrobiology camp at Keio University.",
        "慶應義塾大学の宇宙生物学キャンプを修了。",
      ],
      [
        "2021.03.11",
        "Origin and evolution of life symposium",
        "生命の起原および進化学会シンポジウム",
        "Participated in a symposium on the origin and evolution of life.",
        "生命の起原および進化学会のシンポジウムに参加。",
      ],
      [
        "2021.01–02",
        "JAXA aerospace schools",
        "JAXAエアロスペーススクール",
        "Attended Kakuda Aerospace School on January 29 and Chofu Aerospace School on February 5.",
        "1月29日の角田エアロスペーススクール、2月5日の調布エアロスペーススクールに参加。",
      ],
      [
        "2020.06",
        "University of Queensland Science Masterclass",
        "クイーンズランド大学 Science Masterclass",
        "Completed the Science Masterclass Series for India, an online biology program for school students during the pandemic.",
        "オーストラリア・クイーンズランド大学主催の高校生向けオンライン生物講座を修了。",
      ],
      [
        "2020",
        "University of Toronto engineering symposium",
        "トロント大学 工学シンポジウム",
        "Attended the Young Women in Engineering Symposium.",
        "Young Women in Engineering Symposiumに参加しました。",
      ],
      [
        "—",
        "NASA–JAXA talks and engineering exchange",
        "NASA・JAXA講演、インドの技術者との交流",
        "Attended lectures by NASA and JAXA researchers in two consecutive years, and exchanged ideas with Indian engineers involved in space development.",
        "NASA・JAXA研究者による講演会に2年連続で参加。宇宙開発に携わるインド人技術者とも交流しました。",
      ],
      [
        "—",
        "Pediatric association webinar",
        "日本小児科医会Web講演",
        "Participated in the Japanese Pediatric Association webinar from Sapporo.",
        "「日本小児科医会web講演from札幌」に参加。",
      ],
      [
        "2021–2024",
        "Language and practical qualifications",
        "語学・実務の資格",
        "EIKEN Grade 1 (July 2021), TOEFL iBT 100 (May 2022), Model Rocket License Grade 4 (July 2021), NAUI Open Water Diver (October 2023), and driver’s license (AT, 2024).",
        "英検1級（2021年7月）、TOEFL iBT 100（2022年5月）、モデルロケットライセンス4級（2021年7月）、NAUIオープンウォーターダイバー（2023年10月）、普通自動車免許AT限定（2024年）。",
      ],
    ],
  },
];

// Append to keep the existing archive entry URLs stable.
archiveGroups
  .find((group) => group.id === "research")
  .entries.push([
    codexHackathon.date,
    ...codexHackathon.title,
    ...codexHackathon.summary,
    codexHackathon,
  ]);
