// Generated by scripts/build-gallery-images.py; keep originals for the photo viewer.
export const galleryImages = {
  "svalbard-2025": [
    {
      "src": "assets/images/gallery/responsive/svalbard-2025-400.webp",
      "width": 400,
      "height": 300,
      "bytes": 14904
    },
    {
      "src": "assets/images/gallery/svalbard-2025-thumb.webp",
      "width": 800,
      "height": 600,
      "bytes": 50722
    },
    {
      "src": "assets/images/gallery/responsive/svalbard-2025-1200.webp",
      "width": 1200,
      "height": 900,
      "bytes": 95206
    }
  ],
  "dfki-visit": [
    {
      "src": "assets/images/gallery/responsive/dfki-visit-400.webp",
      "width": 400,
      "height": 534,
      "bytes": 12550
    },
    {
      "src": "assets/images/gallery/responsive/dfki-visit-800.webp",
      "width": 800,
      "height": 1067,
      "bytes": 31126
    },
    {
      "src": "assets/images/gallery/dfki-visit.webp",
      "width": 1054,
      "height": 1406,
      "bytes": 59620
    }
  ],
  "fujiwara-bento": [
    {
      "src": "assets/images/gallery/responsive/fujiwara-bento-400.webp",
      "width": 400,
      "height": 300,
      "bytes": 26458
    },
    {
      "src": "assets/images/gallery/fujiwara-bento-thumb.webp",
      "width": 800,
      "height": 600,
      "bytes": 105656
    },
    {
      "src": "assets/images/gallery/responsive/fujiwara-bento-1200.webp",
      "width": 1200,
      "height": 900,
      "bytes": 232668
    }
  ],
  "georgia-tech-presentation": [
    {
      "src": "assets/images/gallery/responsive/georgia-tech-presentation-400.webp",
      "width": 400,
      "height": 225,
      "bytes": 8078
    },
    {
      "src": "assets/images/gallery/georgia-tech-presentation-thumb.webp",
      "width": 800,
      "height": 450,
      "bytes": 19276
    },
    {
      "src": "assets/images/gallery/responsive/georgia-tech-presentation-1200.webp",
      "width": 1200,
      "height": 675,
      "bytes": 32012
    }
  ],
  "germany-beer-currywurst": [
    {
      "src": "assets/images/gallery/responsive/germany-beer-currywurst-400.webp",
      "width": 400,
      "height": 533,
      "bytes": 31106
    },
    {
      "src": "assets/images/gallery/responsive/germany-beer-currywurst-800.webp",
      "width": 800,
      "height": 1067,
      "bytes": 99292
    },
    {
      "src": "assets/images/gallery/responsive/germany-beer-currywurst-1200.webp",
      "width": 1200,
      "height": 1600,
      "bytes": 183524
    }
  ],
  "bayern-match": [
    {
      "src": "assets/images/gallery/responsive/bayern-match-400.webp",
      "width": 400,
      "height": 533,
      "bytes": 25708
    },
    {
      "src": "assets/images/gallery/responsive/bayern-match-800.webp",
      "width": 800,
      "height": 1067,
      "bytes": 111058
    },
    {
      "src": "assets/images/gallery/responsive/bayern-match-1200.webp",
      "width": 1200,
      "height": 1600,
      "bytes": 239008
    }
  ],
  "shorinji-kempo": [
    {
      "src": "assets/images/gallery/responsive/shorinji-kempo-400.webp",
      "width": 400,
      "height": 400,
      "bytes": 11120
    },
    {
      "src": "assets/images/gallery/shorinji-kempo.webp",
      "width": 535,
      "height": 535,
      "bytes": 19928
    }
  ],
  "singapore-protein": [
    {
      "src": "assets/images/gallery/responsive/singapore-protein-400.webp",
      "width": 400,
      "height": 408,
      "bytes": 12686
    },
    {
      "src": "assets/images/gallery/singapore-protein.webp",
      "width": 604,
      "height": 616,
      "bytes": 30184
    }
  ],
  "bremen-walk": [
    {
      "src": "assets/images/gallery/responsive/bremen-walk-400.webp",
      "width": 400,
      "height": 533,
      "bytes": 31460
    },
    {
      "src": "assets/images/gallery/responsive/bremen-walk-800.webp",
      "width": 800,
      "height": 1067,
      "bytes": 113686
    },
    {
      "src": "assets/images/gallery/responsive/bremen-walk-1200.webp",
      "width": 1200,
      "height": 1600,
      "bytes": 218838
    }
  ],
  "running": [
    {
      "src": "assets/images/gallery/responsive/running-400.webp",
      "width": 400,
      "height": 250,
      "bytes": 11568
    },
    {
      "src": "assets/images/gallery/responsive/running-800.webp",
      "width": 800,
      "height": 499,
      "bytes": 39198
    },
    {
      "src": "assets/images/running.webp",
      "width": 1000,
      "height": 624,
      "bytes": 70230
    }
  ],
  "isas": [
    {
      "src": "assets/images/gallery/responsive/isas-400.webp",
      "width": 400,
      "height": 533,
      "bytes": 20904
    },
    {
      "src": "assets/images/isas.webp",
      "width": 750,
      "height": 1000,
      "bytes": 92888
    }
  ],
  "diving": [
    {
      "src": "assets/images/gallery/responsive/diving-400.webp",
      "width": 400,
      "height": 409,
      "bytes": 3274
    },
    {
      "src": "assets/images/diving.webp",
      "width": 602,
      "height": 616,
      "bytes": 7984
    }
  ],
  "codex-fest-discussion": [
    {
      "src": "assets/images/gallery/responsive/codex-fest-discussion-400.webp",
      "width": 400,
      "height": 267,
      "bytes": 12004
    },
    {
      "src": "assets/images/gallery/responsive/codex-fest-discussion-800.webp",
      "width": 800,
      "height": 534,
      "bytes": 32582
    },
    {
      "src": "assets/images/gallery/responsive/codex-fest-discussion-1200.webp",
      "width": 1200,
      "height": 801,
      "bytes": 54290
    }
  ],
  "codex-fest-badge": [
    {
      "src": "assets/images/gallery/responsive/codex-fest-badge-400.webp",
      "width": 400,
      "height": 267,
      "bytes": 16578
    },
    {
      "src": "assets/images/gallery/responsive/codex-fest-badge-800.webp",
      "width": 800,
      "height": 534,
      "bytes": 41638
    },
    {
      "src": "assets/images/gallery/responsive/codex-fest-badge-1200.webp",
      "width": 1200,
      "height": 801,
      "bytes": 70046
    }
  ],
  "portrait": [
    {
      "src": "assets/images/gallery/responsive/portrait-400.webp",
      "width": 400,
      "height": 400,
      "bytes": 13110
    },
    {
      "src": "assets/images/gallery/responsive/portrait-800.webp",
      "width": 800,
      "height": 800,
      "bytes": 37000
    },
    {
      "src": "assets/images/portrait.webp",
      "width": 1000,
      "height": 1000,
      "bytes": 70400
    }
  ]
};
