import { mkdir, writeFile, readFile, copyFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve, delimiter } from "node:path";
import {
  profile,
  projects,
  education,
  earlierResearch,
  publications,
  awards,
  activities,
  skills,
} from "../content/portfolio.mjs";

// The same public content drives the website and both typeset PDFs.
const tex = (value) =>
  String(value)
    .replace(/[–—−‑]/g, "-")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(
      /[\\{}%&#_$~^]/g,
      (c) =>
        ({
          "\\": "\\textbackslash{}",
          "{": "\\{",
          "}": "\\}",
          "%": "\\%",
          "&": "\\&",
          "#": "\\#",
          _: "\\_",
          $: "\\$",
          "~": "\\textasciitilde{}",
          "^": "\\textasciicircum{}",
        })[c],
    );
const outputDir = resolve("artifacts/latex");
const cacheDir = resolve("artifacts/tex-cache");
await mkdir(outputDir, { recursive: true });
await mkdir(cacheDir, { recursive: true });
const env = {
  ...process.env,
  PATH: ["/Library/TeX/texbin", process.env.PATH]
    .filter(Boolean)
    .join(delimiter),
  TEXMFVAR: cacheDir,
  TEXMFCACHE: cacheDir,
  SOURCE_DATE_EPOCH: String(Date.parse(profile.updated + "T00:00:00Z") / 1000),
};

for (const lang of ["en", "ja"]) {
  const ja = lang === "ja";
  const T = (value) => (Array.isArray(value) ? value[ja ? 1 : 0] : value);
  const entry = ([date, title, description], compact = false) =>
    `\\${compact ? "cvcompact" : "cventry"}{${tex(date === "School years" && ja ? "中学時代" : date)}}{${tex(T(title))}}{${tex(T(description))}}`;
  const section = (title, content) =>
    `\\cvsection{${tex(title)}}\n${content}\n`;
  const page1 = [
    section(
      ja ? "学歴" : "Education",
      education.map((row) => entry(row)).join("\n"),
    ),
    section(
      ja ? "研究・開発" : "Research & Development",
      projects
        .map((p) =>
          entry([
            p.date,
            T(p.title),
            `${p.org} / ${T(p.role)}. ${T(p.summary)}`,
          ]),
        )
        .join("\n"),
    ),
  ].join("\n");
  const page2 = [
    section(
      ja ? "その他の研究" : "Earlier Research",
      earlierResearch.map((row) => entry(row)).join("\n"),
    ),
    section(
      ja ? "発表・執筆" : "Presentations & Papers",
      [...publications]
        .sort((a, b) => b[0].localeCompare(a[0]))
        .map(
          ([date, type, title, venue, url]) =>
            `\\cventry{${tex(date)}}{${url ? `\\href{${tex(url)}}{${tex(T(title))}}` : tex(T(title))}}{${tex(venue)}. ${tex(T(type))}.}`,
        )
        .join("\n"),
    ),
    section(
      ja ? "受賞・採択" : "Awards & Scholarships",
      awards.map((row) => entry(row, true)).join("\n"),
    ),
  ].join("\n");
  const page3 = [
    section(
      ja ? "活動歴" : "Activities",
      activities.map((row) => entry(row)).join("\n"),
    ),
    section(
      ja ? "スキル・資格" : "Skills & Qualifications",
      skills
        .map(
          ([title, desc]) => `\\cvcompact{}{${tex(T(title))}}{${tex(T(desc))}}`,
        )
        .join("\n"),
    ),
  ].join("\n");
  const source =
    `% Generated by scripts/build-cv.mjs from public portfolio content.\n` +
    `\\documentclass[a4paper,10pt]{${ja ? "ltjsarticle" : "article"}}\n` +
    (ja ? "\\usepackage[haranoaji]{luatexja-preset}\n" : "") +
    `\\input{cv/preamble.tex}\n\\hypersetup{pdftitle={${tex(T(profile.name))} - Curriculum Vitae}}\n` +
    `\\begin{document}\n` +
    `{\\fontsize{25}{30}\\selectfont\\bfseries ${tex(T(profile.name))}}` +
    (ja ? "\\hspace{5mm}{\\large Taichi Uchida}" : "") +
    `\\hfill{\\small ${ja ? "2026年9月更新" : "Updated September 2026"}}\\par\\vspace{5pt}\n` +
    `${tex(T(profile.intro))}\\par\\vspace{4pt}\n` +
    `{\\small\\href{mailto:${tex(profile.email)}}{${tex(profile.email)}}\\quad\\textbar\\quad\\href{https://taichi-u.github.io/}{taichi-u.github.io}}\\par\\vspace{4pt}\n` +
    page1 +
    "\\newpage\n" +
    page2 +
    "\\newpage\n" +
    page3 +
    "\\end{document}\n";
  const stem = `taichi-uchida-${lang}`;
  await writeFile(`cv/${stem}.tex`, source);
  for (let pass = 0; pass < 2; pass++) {
    const run = spawnSync(
      process.env.LUALATEX || "lualatex",
      [
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        "-no-shell-escape",
        `-output-directory=${outputDir}`,
        `cv/${stem}.tex`,
      ],
      { env, encoding: "utf8", maxBuffer: 12 * 1024 * 1024 },
    );
    if (run.error || run.status !== 0) {
      console.error(run.error || run.stdout.slice(-9000) + run.stderr);
      process.exit(1);
    }
  }
  const log = await readFile(`${outputDir}/${stem}.log`, "utf8");
  const warnings = log
    .split("\n")
    .filter((line) => /Overfull|Missing character|LaTeX Warning/.test(line));
  if (warnings.length) console.warn(lang + ": " + warnings.join("\n"));
  const output = `cv_taichiuchida${ja ? "-ja" : ""}.pdf`;
  await copyFile(`${outputDir}/${stem}.pdf`, output);
  console.log(`Built ${output} using LuaLaTeX.`);
}
