"""Generate responsive gallery images; requires Pillow and Node.js."""
import json
import subprocess
from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parents[1]
photos = json.loads(subprocess.check_output([
    "node", "--input-type=module", "-e",
    "import { galleryPhotos } from './content/gallery.mjs'; console.log(JSON.stringify(galleryPhotos));",
], cwd=root, text=True))
output = root / "assets/images/gallery/responsive"
output.mkdir(parents=True, exist_ok=True)
manifest = {}
for photo in photos:
    source = root / "assets/images" / (photo["file"] + ".webp")
    thumbnail = source.with_stem(source.stem + "-thumb")
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original).convert("RGB")
    thumbnail_width = None
    if thumbnail.exists():
        with Image.open(thumbnail) as existing:
            thumbnail_width = existing.width
    candidates = []
    for width in sorted({min(size, image.width) for size in (400, 800, 1200)}):
        if width == image.width:
            path = source
        elif thumbnail_width == width:
            path = thumbnail
        else:
            height = round(image.height * width / image.width)
            path = output / f"{photo['id']}-{width}.webp"
            image.resize((width, height), Image.Resampling.LANCZOS).save(
                path, "WEBP", quality=78, method=6
            )
        with Image.open(path) as result:
            candidates.append({
                "src": path.relative_to(root).as_posix(),
                "width": result.width,
                "height": result.height,
                "bytes": path.stat().st_size,
            })
    manifest[photo["id"]] = candidates
(root / "content/gallery-images.mjs").write_text(
    "// Generated by scripts/build-gallery-images.py; keep originals for the photo viewer.\n"
    + "export const galleryImages = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8",
)
print(f"Prepared responsive image candidates for {len(manifest)} photographs.")
